### ISSUE TITLE
Light EDA

### ISSUE THREAD

**Issue by ValleSoYeah** [ValleSoYeah/Machine-Learning-Project_Xente-Fraud-Detection#11]
- [x]  Understand data
- [x]  Look for correlations
- [x]  Make first assumptions

**Comment by ValleSoYeah** [comment]
- [ ] Understand data
- [ ] Find correlations
- [ ] Make first assumptions

**Comment by ValleSoYeah** [comment]
- [x] make a column for incoming/outgoing and drop columns 
- [x] Feature engineering (possibly make dummies already (Valentin)
- [x] Transform date-time into weekday and time of day

**Comment by FlxBckr** [comment]
Valentin:

- [x] Feature engineering

Leonardo:

- [x] Drop `TransactionId, currency_code, country_code, value`
- [x] Transform `Amount` into 0 and 1 (no dummies)

Felix:

- [x] Extract Day / Time / ... from `TransactionStartTime`
